### ISSUE TITLE
Use angular2 CLI to generate this project

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/angular2-codelab#4]

**Comment by Gillespie59** [comment]
What do you need more the work already on on the devoxx branch ?

**Comment by manekinekko** [comment]
@Gillespie59 the migration is fine. I am making sure we track our work ;)

**Comment by manekinekko** [comment]
Oh! I just noticed that the readme.md file is out of sync since the app structure is now different. Could you update the readme.md as well?

**Comment by Gillespie59** [comment]
Yep I will do it.

**Comment by manekinekko** [comment]
@Gillespie59 :+1:

**Comment by Gillespie59** [comment]
Done
