### ISSUE TITLE
Add a branch per step

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/angular2-codelab#7]
anyone interested in taking this one?
cc @cbalit @vogloblinsky @Gillespie59

- [x] step 1: https://github.com/manekinekko/angular2-codelab/tree/step-1-solution
- [x] step 2: https://github.com/manekinekko/angular2-codelab/tree/step-2-solution
- [x] step 3: https://github.com/manekinekko/angular2-codelab/tree/step-3-solution
- [x] step 4: https://github.com/manekinekko/angular2-codelab/tree/step-4-solution
- [x] step 5:  https://github.com/manekinekko/angular2-codelab/tree/step-5-solution
- [x] step 6:  https://github.com/manekinekko/angular2-codelab/tree/step-6-solution
- [x] step 7:  https://github.com/manekinekko/angular2-codelab/tree/step-7-solution

See all details here https://github.com/manekinekko/angular2-codelab/blob/master/STEPS.md

**Comment by manekinekko** [comment]
anyone interested in taking this one?
cc @cbalit @vogloblinsky @Gillespie59

**Comment by Gillespie59** [comment]
Je vais avoir le temps la semaine prochaine. La question c'est quel découpage désirons nous ?

**Comment by manekinekko** [comment]
@Gillespie59 we could create a branch per "angular2 concept/feature". 

For instance:
1. branch 1: root component (basic setup, no routes, no services...just basic)
2. branch 2: add a second component (components composition)
3. branch 3: add a service
4. and so on and so forth...

Does this make sens?

**Comment by cbalit** [comment]
Ok for this branch structure. We should add for each step the starting branch and the solution branch. For example we have the following branches in our sfeirschool

- step-0 angular 2 boostrap and create the first component

- step-1 first template using ngFor

- step-2 first component with form click and ngModel

- step-3 load datas with Http

- step-4 use the router

- step-5 form validation

- step-6 use a Service

- step-7 Angular Pipe

- step-8 create custom Pipe

- step-9 create a Directive

**Comment by cbalit** [comment]
I push a step-1 branch with static files. It's still work in progress but i think we can imagine something like this:

- step-1: build a root component for the angular 2 (boostrap, ts config, ng serve.....)

- step-2: our first componenent-> the theme-card (component,template syntax)

- step-3:  bring the router and service (configuration, router outlet , router link, DI)

- step-4: new page: the quizz and question-card (more template syntax)

- step-5 : the summary page

What do you think of that split ?

**Comment by manekinekko** [comment]
@cbalit awesome! 
Do you think we should add more steps?

**Comment by manekinekko** [comment]
see here: https://github.com/manekinekko/angular2-codelab/blob/master/STEPS.md
work in progress...
